branches:
  only:
  - master

services:
  - gradle

before_script:
  - PROJECT_ROOT_DIR=${PWD}
  - mkdir build
  - mkdir build/asciidoc
  - mkdir build/asciidoc/html5
  - cd build/asciidoc/html5
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git clone -b gh-pages --single-branch https://${GH_REF} .
  - mv .git ../.git
  - rm -rf *
  - mv ../.git .git
  - cd ${PROJECT_ROOT_DIR}

script:
  - gradle asciidoctor

after_success:
  - cd build/asciidoc/html5
  - git add . ; git commit -m "Deploy ${TRAVIS_COMMIT}"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
