sudo: required

services:
  - gradle

script:
  - gradle asciidoctor

after_success:
  - cd build/asciidoc/html5
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
