version: '2'

services:

    rancher:
        image: rancher/server:v1.6.15
        container_name: rancher
        restart: unless-stopped
        networks:
            - server-local
        ports:
            - 8080:8080
    
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - server-local
        ports:
            - 9000:9000

    node:
        image: docker:dind
        container_name: node
        privileged: true
        restart: always
        volumes:
            - ./daemon.json:/etc/docker/daemon.json
        networks:
            - server-local
        ports:
            - 8081:8081

networks:
    server-local:
        driver: bridge
